/**
 * MIT License
 *
 * Copyright (c) 2023 Cunyuan(Holden) Gao 
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 **/

#include "gd2cpp_ast.h"

#ifdef TOOLS_ENABLED
#include "core/io/dir_access.h"

namespace gd2cpp::cppast {
  Program::Program(): main_class{nullptr}, lead_comment{"/* Generated By GD2Cpp. DO NOT modify. */\n"} {
  }

  Program::~Program() {
    if (main_class != nullptr) {
      memdelete(main_class);
    }
  }

  Program* Program::create(Class* p_cls, const String& p_header, const String& p_source) {
    Program* prog = memnew(Program);
    prog->main_class = p_cls;
    prog->header_path = p_header;
    prog->source_path = p_source;
    return prog;
  }

  String Program::to_header() {
    return lead_comment + main_class->to_header(); // TODO
  }

  String Program::to_source() {
    String res = lead_comment;
    res += gen_include(header_path);
    res += main_class->to_source();
    return res;
  }

  String Program::gen_include(const String& p_filename) {
    Error err;
    Ref<FileAccess> to = FileAccess::open(p_filename, FileAccess::READ, &err);
    return "#include \"" + to->get_path_absolute()  + "\"\n";
  }

  void Program::save() {
    save(header_path, to_header());
    save(source_path, to_source());
  }

  void Program::save(const String& p_filename, const String& p_content) {
    Error err;
    const String path = p_filename.get_base_dir();
    Ref<DirAccess> dir = DirAccess::open("res://", &err);
    if (!dir->dir_exists(path)) {
      err = dir->make_dir_recursive(path);
      if (err != OK) {
        print_error("Cannot create directory " + path + ".");
        return;
      }
    }

	  Ref<FileAccess> file = FileAccess::open(p_filename, FileAccess::WRITE, &err);
    if (err != OK) {
      print_error("Cannot save LLVM file " + p_filename + ".");
    }
    else {
      file->store_string(p_content);
    }
  }

  Class* Class::create() {
    Class* cls = memnew(Class);
    return cls;
  }

  String Class::to_header() {
    return ""; // TODO
  }

  String Class::to_source() {
    return ""; // TODO
  }
} // namespace gd2cpp::cppast

#endif
