#!/usr/bin/env python

Import("env")
Import("env_modules")

env_gd2cpp = env_modules.Clone()

env_gd2cpp.add_source_files(env.modules_sources, "*.cpp")

if env.editor_build:
  env_gd2cpp.add_source_files(env.modules_sources, "./editor/*.cpp")
