#!/usr/bin/env python
import os
import sys

env = SConscript("godot-cpp/SConstruct")

env.Append(CPPPATH=["natives/src/"])
sources = Glob("natives/src/*.cpp")

if env["platform"] == "macos":
  library = env.SharedLibrary(
      "game/bin/libgdsummator.{}.{}.framework/libgdsummator.{}.{}".format(
          env["platform"], env["target"], env["platform"], env["target"]
      ),
      source=sources,
  )
else:
  library = env.SharedLibrary(
      "game/bin/libgdsummator{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
      source=sources,
  )

Default(library)
